### ISSUE TITLE
Seeed Studio Contributor Program

### ISSUE THREAD

**Issue by MatthewJeffson** [Echo7394/EcoStat#1]
Hi Chris!
It is nice to meet you. I'm Matthew from Seeed Studio and I'm responsible for our little program called "[Contributor Program](https://github.com/orgs/Seeed-Studio/projects/6/views/1?pane=issue&itemId=30957479)". Your project here is so interested and very attached to our recent theme: Home Assistant.

Hence, may I ask if you are interested redoing this project, by using our products(Grove modules)? And let it be able to be controlled and viewed the data on Home Assistant devices?
Here is a reference: [XIAO ESP32C3 connecting with Home Assistant via ESPHome(all ports supported)](https://wiki.seeedstudio.com/XIAO-ESP32C3-for-ESPHome-Support/)

A working demo and wiki contents will be fine. I will create an assignment and assigned to you in our program.
Really looking forward our operation.
Best Regards,
Matthew

**Comment by Echo7394** [comment]
I would be extremely happy to create a version of EcoStat that supports Home Assistant using Grove modules. Would you or anyone at Seeed Studio be willing to provide demo hardware (a Xiao ESP32C3 or S3 and Grove Modules) to use for testing and development as well as to create a demo video with?

**Comment by MatthewJeffson** [comment]
Hello! Sure I can and happy to ask some hardware for you :)
May we contact with email so we can discuss privately.
Best Regards,
Matthew

**Comment by Echo7394** [comment]
Absolutely, my E-Mail is echo7394@protonmail.com
